### PR TITLE
v2.0 Implement reverse cholesky

### PR DESCRIPTION
**Pull request by dlfivefifty**
@MikaelSlevinsky @TSGut @ioannisPApapadopoulos 

FYI. Once tests are passing I'll make it restrict to only accessing `colsupport` which should automatically support banded matrices.

I don't think we are desperate for adaptive reverse Cholesky at the moment in ∞ dimensions, but I'll probably leave that to @TSGut if we need it....

### CODE REVIEW

**Comment by TSGut** [comment]
Cool! Yes, with reverse Cholesky available it will be easy to do adaptive reverse Cholesky with the adaptive QL template if we end up wanting it.

**Comment by dlfivefifty** [comment]
reverse Cholesky up to `p = 1 billion`! (God I need more RAM)

image

**Comment by TSGut** [comment]
Who needs adaptivity if you can just do infinity directly.

**Comment by dlfivefifty** [comment]
Need more than 16 GB of RAM for that

**Pull request merged**
